
development-environment:
  build: development
  container_name: development-environment
  hostname: development-environment
  ports:
  - "2223:22"
  volumes:
  - "./development/config/.ssh:/.ssh"
  - "./development/playground:/home/ubuntu/playground"
  environment:
  - USER=ubuntu
  
